<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HIREN" name="Default test(failed)" tests="2" failures="2" timestamp="31 Jan 2016 17:38:44 GMT" time="0.071" errors="0">
  <testcase name="" time="0.007" classname="springmvc.model.dao.UserDaoTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at springmvc.model.dao.UserDaoTest.getUser(UserDaoTest.java:18)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:172)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!--  -->
  <testcase name="" time="0.009" classname="springmvc.model.dao.UserDaoTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at springmvc.model.dao.UserDaoTest.getUsers(UserDaoTest.java:24)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:172)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!--  -->
</testsuite> <!-- Default test(failed) -->
